site_name: My Docs
site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production
site_url: https://darkdealnet.github.io/jwtserver/
theme:
  name: material
  language: en

extra:
  alternate:
    - name: Russian
      link: /ru/
      lang: ru

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

