site_name: JWTServer
site_author:
site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production
site_url: https://darkdealnet.github.io/jwtserver/
copyright: sdfsdffd
repo_url: https://github.com/darkdealnet/jwtserver
theme: readthedocs

nav:
  - index.md

#theme:
#  features:
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.indexes
#    - toc.integrate
#  name: material
#  locale: ru
#  language: ru
#
#extra:
#  alternate:
#    - name: English
#      link: en/
#      lang: en
#    - name: Russian
#      link: ru/
#      lang: ru
#
#plugins:
#  - search:
#      lang:
#        - en
#        - ru
#
#
#markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true
#  - smarty
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
#
#
